import * as faIcons from "react-icons/fa";
import * as mdIcons from "react-icons/md";
import * as tbIcons from "react-icons/tb";

// ================= IMPORTS =================
// ================= MAP =================
export const electronicsIcons = {
  // ================= 🌐 CONNECTIVITY =================
  wifi: faIcons.FaWifi,
  bluetooth: faIcons.FaBluetooth,
  mobileData: faIcons.FaSignal,
  hotspot: mdIcons.MdWifiTethering,
  airplaneMode: faIcons.FaPlane,
  ethernet: faIcons.FaNetworkWired,
  vpn: faIcons.FaLock,
  nfc: mdIcons.MdNfc,
  gps: mdIcons.MdGpsFixed,
  usb: faIcons.FaUsb,
  tower: faIcons.FaBroadcastTower,
  data: mdIcons.MdDataUsage,
  thunderbolt: mdIcons.MdUsb,
  sim: faIcons.FaSimCard,
  esim: mdIcons.MdSimCard,
  signal: mdIcons.MdNetworkCell,

  // ================= 💻 DEVICES =================
  computer: mdIcons.MdComputer,
  desktop: tbIcons.TbDeviceDesktop,
  laptop: mdIcons.MdLaptop,
  tablet: mdIcons.MdTablet,
  phone: mdIcons.MdPhoneAndroid,
  phoneAlt2: tbIcons.TbPhone,
  phoneAlt: tbIcons.TbDeviceMobile,
  laptopAlt: tbIcons.TbDeviceLaptop,

  // ================= 🧩 HARDWARE =================
  display: tbIcons.TbDeviceDesktop,
  touchscreen: mdIcons.MdTouchApp,
  keyboard: faIcons.FaKeyboard,
  mouse: faIcons.FaMouse,
  webcam: faIcons.FaCamera,
  microphone: faIcons.FaMicrophone,
  speakers: faIcons.FaVolumeUp,
  headphoneJack: faIcons.FaHeadphones,
  chip: faIcons.FaMicrochip,
  fan: faIcons.FaFan,
  memory: mdIcons.MdMemory,
  cpu: tbIcons.TbCpu,
  usbAlt: mdIcons.MdUsb,
  ram: faIcons.FaMemory,
  storage: faIcons.FaHdd,
  ssd: mdIcons.MdStorage,
  sdcard: faIcons.FaSdCard,
  battery: faIcons.FaBatteryFull,
  charger: faIcons.FaPlug,
  fingerprint: faIcons.FaFingerprint,
  faceRecognition: mdIcons.MdFace,

  // ================= 📱 SENSORS =================
  accelerometer: mdIcons.MdScreenRotation,
  gyroscope: tbIcons.TbRotateClockwise,
  magnetometer: mdIcons.MdExplore,
  lightSensor: faIcons.FaSun,
  proximitySensor: mdIcons.MdSensors,

  // ================= 📲 SOFTWARE =================
  phoneApp: faIcons.FaPhone,
  contacts: faIcons.FaAddressBook,
  messages: faIcons.FaSms,
  email: faIcons.FaEnvelope,
  browser: faIcons.FaGlobe,
  appStore: faIcons.FaStore,
  settings: faIcons.FaCog,
  notifications: faIcons.FaBell,
  clock: faIcons.FaClock,
  calendar: faIcons.FaCalendarAlt,
  calculator: faIcons.FaCalculator,
  gallery: faIcons.FaImage,
  videoPlayer: faIcons.FaVideo,
  musicPlayer: faIcons.FaMusic,
  fileManager: faIcons.FaFolder,
  recorder: faIcons.FaMicrophoneAlt,
  rotation: tbIcons.TbRotate,
  brightness: mdIcons.MdBrightnessMedium,
  volume: tbIcons.TbVolume,
  doNotDisturb: mdIcons.MdDoNotDisturb,
  flashlight: mdIcons.MdFlashlightOn,
  screenshot: mdIcons.MdScreenshot,
  screenRecord: mdIcons.MdScreenShare,
  assistant: faIcons.FaRobot,
  taskManager: faIcons.FaTasks,
  update: mdIcons.MdUpdate,
  antivirus: faIcons.FaShieldAlt,
  firewall: mdIcons.MdSecurity,

  // ================= 🔌 PORTS =================
  usbPort: tbIcons.TbUsb,
  displayPort: tbIcons.TbScreenShare,
  audioJack: tbIcons.TbHeadphones,
  chargingPort: tbIcons.TbPlug,

  // ================= 📊 STATUS =================
  batteryFull: faIcons.FaBatteryFull,
  batteryHalf: faIcons.FaBatteryHalf,
  batteryLow: faIcons.FaBatteryEmpty,
  charging: tbIcons.TbBatteryCharging,
  wifiSignal: tbIcons.TbWifi,
  bluetoothStatus: tbIcons.TbBluetooth,
  storageStatus: tbIcons.TbDatabase,
  cpuUsage: tbIcons.TbCpu,
  temperature: tbIcons.TbTemperature,
  lowPower: tbIcons.TbBatteryOff,
  silent: faIcons.FaMoon,
  vibrate: mdIcons.MdVibration,
  mapMarker: faIcons.FaMapMarkerAlt,
};