// ================= IMPORTS =================
import {
  FaWifi,
  FaBluetooth,
  FaSignal,
  FaBroadcastTower,
  FaPlane,
  FaNetworkWired,
  FaLock,
  FaMapMarkerAlt,
  FaUsb,
  FaSimCard,

  FaKeyboard,
  FaMouse,
  FaMicrophone,
  FaHeadphones,
  FaCamera,
  FaVideo,
  FaFan,
  FaMicrochip,
  FaMemory,
  FaHdd,
  FaSdCard,
  FaBatteryFull,
  FaPlug,
  FaFingerprint,

  FaPhone,
  FaAddressBook,
  FaSms,
  FaEnvelope,
  FaGlobe,
  FaStore,
  FaCog,
  FaBell,
  FaClock,
  FaCalendarAlt,
  FaCalculator,
  FaImage,
  FaMusic,
  FaFolder,
  FaMicrophoneAlt,
  FaSun,
  FaVolumeUp,
  FaMoon,
  FaRobot,
  FaTasks,
  FaShieldAlt,

  FaBatteryHalf,
  FaBatteryEmpty,
} from "react-icons/fa";

import {
  MdWifiTethering,
  MdDataUsage,
  MdNfc,
  MdGpsFixed,
  MdUsb,
  MdScreenRotation,
  MdBrightnessMedium,
  MdDoNotDisturb,
  MdFlashlightOn,
  MdScreenshot,
  MdScreenShare,
  MdUpdate,
  MdSecurity,
  MdStorage,
  MdMemory,
  MdComputer,
  MdLaptop,
  MdTablet,
  MdPhoneAndroid,
  MdTouchApp,
  MdSimCard,
  MdNetworkCell,
  MdFace,
  MdExplore,
  MdSensors,
  MdVibration
} from "react-icons/md";

import {
  TbDeviceDesktop,
  TbDeviceLaptop,
  TbDeviceMobile,
  TbCpu,
  TbTemperature,
  TbVolume,
  TbBatteryCharging,
  TbPhone,
  TbRotate,
  TbRotateClockwise,
  TbUsb,
  TbScreenShare,
  TbHeadphones,
  TbPlug,
  TbWifi,
  TbBluetooth,
  TbDatabase,
  TbBatteryOff
} from "react-icons/tb";

// ================= MAP =================
export const electronicsIcons = {
  // ================= 🌐 CONNECTIVITY =================
  wifi: FaWifi,
  bluetooth: FaBluetooth,
  mobileData: FaSignal,
  hotspot: MdWifiTethering,
  airplaneMode: FaPlane,
  ethernet: FaNetworkWired,
  vpn: FaLock,
  nfc: MdNfc,
  gps: MdGpsFixed,
  usb: FaUsb,
  tower: FaBroadcastTower,
  data: MdDataUsage,
  thunderbolt: MdUsb,
  sim: FaSimCard,
  esim: MdSimCard,
  signal: MdNetworkCell,

  // ================= 💻 DEVICES =================
  computer: MdComputer,
  desktop: TbDeviceDesktop,
  laptop: MdLaptop,
  tablet: MdTablet,
  phone: MdPhoneAndroid,
  phoneAlt2: TbPhone,
  phoneAlt: TbDeviceMobile,
  laptopAlt: TbDeviceLaptop,

  // ================= 🧩 HARDWARE =================
  display: TbDeviceDesktop,
  touchscreen: MdTouchApp,
  keyboard: FaKeyboard,
  mouse: FaMouse,
  webcam: FaCamera,
  microphone: FaMicrophone,
  speakers: FaVolumeUp,
  headphoneJack: FaHeadphones,
  chip: FaMicrochip,
  fan: FaFan,
  memory: MdMemory,
  cpu: TbCpu,
  usbAlt: MdUsb,
  ram: FaMemory,
  storage: FaHdd,
  ssd: MdStorage,
  sdcard: FaSdCard,
  battery: FaBatteryFull,
  charger: FaPlug,
  fingerprint: FaFingerprint,
  faceRecognition: MdFace,

  // ================= 📱 SENSORS =================
  accelerometer: MdScreenRotation,
  gyroscope: TbRotateClockwise,
  magnetometer: MdExplore,
  lightSensor: FaSun,
  proximitySensor: MdSensors,

  // ================= 📲 SOFTWARE =================
  phoneApp: FaPhone,
  contacts: FaAddressBook,
  messages: FaSms,
  email: FaEnvelope,
  browser: FaGlobe,
  appStore: FaStore,
  settings: FaCog,
  notifications: FaBell,
  clock: FaClock,
  calendar: FaCalendarAlt,
  calculator: FaCalculator,
  gallery: FaImage,
  videoPlayer: FaVideo,
  musicPlayer: FaMusic,
  fileManager: FaFolder,
  recorder: FaMicrophoneAlt,
  rotation: TbRotate,
  brightness: MdBrightnessMedium,
  volume: TbVolume,
  doNotDisturb: MdDoNotDisturb,
  flashlight: MdFlashlightOn,
  screenshot: MdScreenshot,
  screenRecord: MdScreenShare,
  assistant: FaRobot,
  taskManager: FaTasks,
  update: MdUpdate,
  antivirus: FaShieldAlt,
  firewall: MdSecurity,

  // ================= 🔌 PORTS =================
  usbPort: TbUsb,
  displayPort: TbScreenShare,
  audioJack: TbHeadphones,
  chargingPort: TbPlug,

  // ================= 📊 STATUS =================
  batteryFull: FaBatteryFull,
  batteryHalf: FaBatteryHalf,
  batteryLow: FaBatteryEmpty,
  charging: TbBatteryCharging,
  wifiSignal: TbWifi,
  bluetoothStatus: TbBluetooth,
  storageStatus: TbDatabase,
  cpuUsage: TbCpu,
  temperature: TbTemperature,
  lowPower: TbBatteryOff,
  silent: FaMoon,
  vibrate: MdVibration,
  mapMarker: FaMapMarkerAlt,
};